### ISSUE TITLE
Windows browse file chooser located on JavaFx app not working 

### ISSUE THREAD

**Issue by dhananjaym18** [renatoathaydes/Automaton#30]
I have written a groovy script to click on a "Choose File..." button on a javaFx app, which opens Windows open file action window. Now I would like to select a file from a particular folder and click on "Open" button. My Automaton/Grovvy scripts dont seem to do anything on this Windows based pop-up box. 

clickOn 'text:Attachment 2:'
moveBy( 150, 0 )
click()
clickOn 'text:File name:'
moveBy( 50, 0 )
click()
enterText 'D:\\Automaton_test\\Hello\\abc.xml'
clickOn 'text:Open'

Please help figure this out. 

I basically want to be able to choose a file from the "Choose File.." button on my JavaFx application

**Comment by renatoathaydes** [comment]
Very sorry, but Automaton selectors support only access to Swing/JavaFX components. The file chooser is OS-specific and is not part of Java's windowing system.

You can still use Automaton to type things on that window, but this will be difficult to do right if you need to click on a button, for example...

You could try to move by coordinates (assuming you always test on the same screen-size, this could work as the OS's file chooser probably will always show up in the same location) using `moveTo( 500, 600 )` or `moveBy( 100, 240 )` for example. Most functions will work, for example:

```groovy
driver.type( "Automaton" ).type( KeyEvent.VK_ENTER );
```

As long as you do not use String selectors, things will work.

There's a documentation page showing how you can use Automaton's [platform-independent functions](https://github.com/renatoathaydes/Automaton/blob/master/docs/no-platform.md).

**Comment by dhananjaym18** [comment]
Thanks, that helped !
