### ISSUE TITLE
TextFxSelector bug

### ISSUE THREAD

**Issue by akabachkov** [renatoathaydes/Automaton#38]
There is a Bug in implementation of of TextFxSelector.matches. It checks just method name, but not argument existance(SwingUtil.callMethodIfExists( node, 'getText' ) instead of SwingUtil.callMethodIfExists( node, 'getText' ,[])). It easy to reproduce if there is a table on the form and You want to find a component with text: selector. When it comes to TableHeaderRow the next exception arises, because of TableHeaderRow has method getText, but with arguments:

groovy.lang.MissingMethodException: No signature of method: com.sun.javafx.scene.control.skin.TableHeaderRow.getText() is applicable for argument types: () values: []
Possible solutions: getAt(java.lang.String), getClip(), getEffect(), getId(), getParent(), getScene()

**Comment by renatoathaydes** [comment]
thank you for reporting. If you want, feel free to submit a PR... if not, I can do it.

**Comment by renatoathaydes** [comment]
Hi.

I had a look and it seems this should not happen in the latest version: `1.3.1-beta`.

Could you please confirm whether this problem happens even on this version??

**Comment by akabachkov** [comment]
Yes, in 1.3.1-beta it works. Thanks.
