### ISSUE TITLE
Make Automaton available in the Maven central repository

### ISSUE THREAD

**Issue by AlexanderZobkov** [renatoathaydes/Automaton#42]
To increase availability of and attention to this great testing framework it would be great to make it available in the Maven central as well. Probably the Maven central repo has no all features and capabilities that Bintray/Jcenter provides but the Maven central repo is a well known repository and it does not require for Maven users special configuration to download artifacts from it. In addition, for conservative/lazy/legacy developers, absence of this or that library in the Maven central repo might be a bad sign or a sign that something needs to be re-configured in existing build infrastructure that he/she don't want or can't do.

**Comment by renatoathaydes** [comment]
Yeah, I would like to do that! I will try for the next release.

**Comment by AlexanderZobkov** [comment]
I would suggest to publish Automaton 1.2.3 and the latest beta(s) to the Maven central if it does not require a lot of effort. And does not wait for next releases.

**Comment by renatoathaydes** [comment]
I've started the process! Let's see how long it will take for them to respond.

**Comment by renatoathaydes** [comment]
I will release version 1.3.1 (un-released yet) because dependencies need to be updated, and some important changes have been made in the beta versions (1.3.0-beta and 1.3.1-beta)....

**Comment by renatoathaydes** [comment]
Version 1.3.2 is on Maven Central but it still requires Swing-selectors from JCenter... will close this issue once swing-selectors is also on Maven Central

**Comment by renatoathaydes** [comment]
All good now... automaton version `1.3.2` and swing-selectors `1.0` are on Maven Central!

@AlexanderZobkov hope that helps!
