### ISSUE TITLE
Exceptions thrown in a groovy script run by the javaagent does not terminate application under test

### ISSUE THREAD

**Issue by AlexanderZobkov** [renatoathaydes/Automaton#44]
Groovy scripts run by the javaagent can throw exceptions. For example, 
````
clickOn 'text:Submit'
clickOn 'text:XXXXX'  -> throws an exception
````
````
groovy.lang.MissingMethodException: No signature of method: com.sun.javafx.scene.control.skin.TableHeaderRow.getText() is applicable for argument types: () values: []                               
Possible solutions: getAt(java.lang.String), getClip(), getEffect(), getId(), getParent(), getScene()                                                                                                
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)                                                                                                   
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:170) 
... stack is omitted ...

        at Script1.run(Script1.groovy:6)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:591)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:629)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:600)
        at groovy.lang.GroovyShell$evaluate.call(Unknown Source)
````
Current behavior just leaves application to run and tester with no sign that something went wrong

**Comment by renatoathaydes** [comment]
Oh, didn't expect that! Thanks for reporting, I will fix ASAP.

**Comment by renatoathaydes** [comment]
Can you post the JVM version you're using? Looks like the `TableHeaderRow` you've got doesn't have `getText` but Automaton tried to call that, which would be very weird (as Automaton checks if the method exists first!).

**Comment by AlexanderZobkov** [comment]
If it will help to throubleshoot easier, I'm using Automaton 1.2.3

**Comment by renatoathaydes** [comment]
I'd forgotten that the `getText()` bug you have faced is fixed in the latest beta version, but not in the latest stable version `1.2.3`. Please use version `1.3.1-beta` and see how it goes (it has one more dependency by the way, as I externalized swing selectors to its own project, which is also on jcenter: https://github.com/renatoathaydes/Swing-Selectors.

**Comment by AlexanderZobkov** [comment]
Yes, It looks like the groovy.lang.MissingMethodException gone in 1.3.1-beta. 
However, the issue is not in this this particular exception but in fact that the application continue to run when exceptions are thrown inside an AScript. If AScripts were designed to do automatic non-interactive testing then tester should be able to immediately understand that things went wrong, for example application under test immediate shutdown and non-zero error code .

**Comment by renatoathaydes** [comment]
Yeah, I know that... just wanted to let you know about the fix.

**Comment by renatoathaydes** [comment]
@AlexanderZobkov  Could you please try version `1.3.2-beta`, which should've fixed this issue?
Let me know if it's good now.
