### ISSUE TITLE
How do i click on 'Yes' or 'No' option in JOptionPane.showConfirmDialog 

### ISSUE THREAD

**Issue by loma** [renatoathaydes/Automaton#50]
In my existing code, it show the confirm box before proceed.
How do I click on button on the popup window?

**Comment by renatoathaydes** [comment]
Hi!

Here's how you do it:

```groovy
driver.clickOn( 'clickme' ) // click on some button that makes the popup show up
    .pause( 250 ) // takes a little time for the popup to show up
    .clickOn( 'text:Yes' ) // which button to click? Select it by text
```

I've added this test to confirm this works:

https://github.com/renatoathaydes/Automaton/commit/0533ff70e451214ecab76ca4a333720c5ccca43d
