### ISSUE TITLE
Clicking the same location twice doesn't work

### ISSUE THREAD

**Issue by nathanabercrombie** [renatoathaydes/Automaton#51]
I have multiple screens with "next" buttons.  If I have the automaton click the next button of one screen, then wait, and then click the next button of a next screen, then the button doesn't actually get clicked.  (Note: they have different Id, so the component is correctly found).

My workaround was to jiggle the mouse with .move(1, 0).move(-1, 0).

**Comment by renatoathaydes** [comment]
Try `doubleClick()` or just `click().pause(100).click()`.

Just calling `click()` too fast will be interpreted by the computer as a single click as no user can click so fast :)

**Comment by nathanabercrombie** [comment]
It wasn't because of that.  There is a 500ms pause in between.

I am now having the issue for different locations, too.  click() doesn't seem to always work.  Does anything need to be done to get it to be reliable?

I can see the mouse move to the button, but then it doesn't get clicked.

**Comment by nathanabercrombie** [comment]
this is my current workaround, that also fixes the new issue:

`
    public void waitForCurrentEventsToFinish() {
        try {
            jiggleMouse();

            // Sleep so that we can:
            //  - ensure the operating system has passed the event to the app
            //  - make the automation easier to watch
            Thread.sleep(500);

            jiggleMouse();

            // Wait for the event queue to empty
            // As the "Click" travels through the Swing app
            EventQueue.invokeAndWait(new Runnable() {
                @Override
                public void run() { }
            });
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private void jiggleMouse() {
        // Jiggle the mouse, or else the automation doesn't seem to work sometimes
        // (clicking the same location twice doens't seem to work in automation)
        automation.moveBy(1, 0).moveBy(-1, 0);
    }`

**Comment by renatoathaydes** [comment]
When you call `click()`, Automaton sends the exact same signal as a real mouse click. This is reliable and if you don't get the event you expect it's because of something else. I noticed that JavaFX applications tend to not always capture mouse clicks (but this may be also true in Swing). I don't know the fundamental reason, but I believe it's a problem in the OS's windowing framework itself or how Java interacts with it.
