### ISSUE TITLE
how to use another window in groovy script?

### ISSUE THREAD

**Issue by x1nas** [renatoathaydes/Automaton#55]
I use [manual](https://github.com/renatoathaydes/Automaton/blob/master/docs/running-scripts.md) to run groovy script from command line.
First window of my-app.jar - login window.
After login another window opens.
How to catch and use another window?

**Comment by x1nas** [comment]
Found this solution:
```
import com.athaydes.automaton.Swinger;
import java.awt.Window;
swinger = Swinger.getUserWith( Window.windows[1] );
swinger.clickOn( "text:OK" )
```

**Comment by renatoathaydes** [comment]
`Swinger.forSwingWindow()` should do the same.

**Comment by x1nas** [comment]
> Swinger.forSwingWindow() should do the same.

Doesn't work for me:

> AScript failed due to com.athaydes.automaton.GuiItemNotFound: Component not showing on screen:

**Comment by renatoathaydes** [comment]
`Swinger.forSwingWindow()` takes the first window available... in your example, you take the second one, so that explains why my suggestion didn't work..

If you have more than one windows, you should select the right window.. .Try to find it by name to make your test more reliable. Example:

```groovy
myAppWindow = Window.windows.find { it.name == 'My App' }
if (!myAppWindow) throw new Exception("Could not find my window")
```
