### ISSUE TITLE
How to interact with editable combobox?

### ISSUE THREAD

**Issue by x1nas** [renatoathaydes/Automaton#57]
[from manual:](https://github.com/renatoathaydes/Automaton/blob/master/docs/getting-started-swing.md#comparison-with-fest-swing)
example for FEST-Swing:
> dialog.comboBox("domain").select("Users");

example for Automaton:
> swinger.clickOn( "domain" )
>        .clickOn( "text:Users" )

clickOn editable ComboBox doesn't open ComboBox menu (cursor clicks on center of editable text field).
Is there any way to open ComboBox menu with Automaton?
How to click on ComboBoxButton?
How to get coordinates of ComboBoxButton ?

**Comment by renatoathaydes** [comment]
Please try this:

Groovy:

```groovy
swinger[ JComboBox ].showPopup()
swinger.clickOn( 'text:Users' )
```

Java:

```java
swinger.getAt( JComboBox.class ).showPopup();
swinger.clickOn( "text:Users" );
```

**Comment by renatoathaydes** [comment]
The coordinates of a Swing Component can be found using this method: `com.athaydes.automaton.SwingAutomaton#centerOf`.

**Comment by x1nas** [comment]
Thanks, it works!
