### ISSUE TITLE
Gradle fails

### ISSUE THREAD

**Issue by elect86** [renatoathaydes/Automaton#59]
Hi,

I just cloned and tried to sync Gradle, but this is what I get

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Users\gBarbieri\IdeaProjects\Automaton\build.gradle' line: 172
> 
> * What went wrong:
> A problem occurred evaluating root project 'Automaton'.
> > Could not find property 'ossrhUsername' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@1259e718.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 0.187 secs
> Could not find property 'ossrhUsername' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@1259e718.
>

**Comment by renatoathaydes** [comment]
Did you use `gradlew`?

**Comment by renatoathaydes** [comment]
Oh, the error you got is related to the release credentials, which I should not make mandatory for builds.... I will fix!

**Comment by renatoathaydes** [comment]
Thanks for letting me know @elect86 .... it's fixed now.
